### ISSUE TITLE
Wot no fishes?

### ISSUE THREAD

**Issue by hugmyster** [ahuff44/sublime-fish-tank#2]
I launched the **Fish Tank** link to Sublime Text 3 but to no avail - my tank remains empty and barren. My home-written mobile aquarium is OK... but limited.

This is running on Windows under the MobaXTerm. I don't know if this helps - some of it is somewhat beyond me!

**Comment by ahuff44** [comment]
hmm, it's working for me on the latest build of ST3 (build 3143)

my exact steps that I just did:
1. open sublime
2. create new file
3. paste in a bunch of text from anywhere (the fish tank doesn't work on empty files... maybe I should change that)
4. ctrl+shift+p to launch command palette
5. choose "Fish Tank: Normal" from command palette
6. there are now "fish" on my screen

Have you used this before, and it recently broke for some reason? Or is this the first time you've tried to use it?

**Comment by hugmyster** [comment]
Sorry, this is a VERY late reply!

I've not used it before, no, but needed a 'screensaver'. Or some fishes. Or
a reason to reply to my emails, "Just gone fishing"...

I'll try that - thanks!

**Comment by hugmyster** [comment]
Banzai! Took a few attempts to persuade it but it does work.

Thank you very much indeed. :o)

**Comment by ahuff44** [comment]
glad to hear it's working! enjoy :)
